name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install

      - name: Build SPA
        run: pnpm build

      - name: Push ./dist to master:gh-pages
        working-directory: ./dist
        run: |
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${GITHUB_ACTOR}"
          git init
          git add --all
          git commit -m "Auto update pages on $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
